name: Fibonacci app  

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
on:
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile.dev --tag react_app_dev:latest
#      shell: bash
#      run: echo $pwd
    - name: test docker compose
      run: docker-compose version
      shell: bash
    - name: Docker compose UP 
      run: docker-compose -f docker-compose.yml up -d 
      shell: bash
    - name: Test 1
      run: |
        docker ps
        sleep 60
    - name: Docker-compose-down
      run: docker-compose down -v
    - name: Test2
      run: |
        sleep 60
        docker ps
    - name: Docker compose UP 
      run: docker-compose -f docker-compose.yml up -d
    - name: Test3
      run: |
        sleep 120
        docker ps
        curl -v localhost:3050/api/values/all
    - name: Test4
      run: docker exec -it react-app-complex_nginx_1 systemctl status ngnix
    - name: test5
      run: docker exec -it react-app-complex_nginx_1 ps aux
    - name: test6
      run: docker exec -it react-app-complex_nginx_1 cat /var/log/nginx/error.log
      
